# Generated by Django 4.2.7 on 2023-11-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
    ]
