# Generated by Django 4.2.7 on 2023-11-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.foodcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='recipe',
            field=models.TextField(blank=True, null=True, verbose_name='Recipe'),
        ),
    ]
