# Generated by Django 4.2.7 on 2023-11-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_userweight_usercalories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userweight',
            name='user',
        ),
    ]
