# Generated by Django 4.2.7 on 2023-11-18 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_userweight_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalorieGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_goal', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Calorie goal')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
            ],
        ),
        migrations.RemoveField(
            model_name='usercalories',
            name='user',
        ),
    ]
