# Generated by Django 4.2.7 on 2023-11-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_usercaloriegoal_remove_usercalories_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userweight',
            options={'ordering': ('-created_at',)},
        ),
    ]
