# Generated by Django 4.2.7 on 2023-11-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_usercaloriestotal_alter_usercalories_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercalories',
            name='time_of_day',
            field=models.CharField(default='Breakfast', max_length=50, verbose_name='Time of day'),
        ),
    ]
