# Generated by Django 4.2.7 on 2023-11-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_foodlog_delete_user_remove_usercalories_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_product', to='main.foodcategory', verbose_name='Category'),
        ),
    ]
