# Generated by Django 4.2.7 on 2023-11-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_usercaloriesgoal_calorie_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='time_of_day',
            field=models.CharField(max_length=50, verbose_name='Time of day'),
        ),
    ]
