# Generated by Django 4.2.7 on 2023-11-21 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_foodlog_options_remove_foodlog_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='consumed_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7, verbose_name='Portion weight (g)'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='consumed_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True, verbose_name='created at'),
        ),
    ]
