# Generated by Django 4.2.7 on 2023-11-21 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_foodlog_consumed_amount_foodlog_consumed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='consumed_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, null=True, verbose_name='created at'),
        ),
    ]
